apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nb-base
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay-cnhmj.apps.cluster-cnhmj.dynamic.redhatworkshops.io/tssc/nb-base:07b437cfadea7bc62240d69e5fa4aef01db700cc@sha256:1402ac8a6d4181783c1b4a88938f4218b7cc445b8fae5c9661f22dcb4437faa3
          name: container-image
