apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nb-base
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay-cnhmj.apps.cluster-cnhmj.dynamic.redhatworkshops.io/tssc/nb-base:0fa517cbea9cebbd77f9ecb221ad0099adee9657@sha256:46ca8a301c130651cc65ab2f73b79a15befb02cd4ef9b055915107ec8493e223
          name: container-image
