apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nb-base
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay-cnhmj.apps.cluster-cnhmj.dynamic.redhatworkshops.io/tssc/nb-base:e40c556d42a32586ea68ac816d024aa219335ea0@sha256:84f0fbdc7ceac3927bb9e6664953ec0b10de71bbb7f60d336f20739043d9590f
          name: container-image
